"""add_schedule_fields_to_scheme

Revision ID: feeb34b76742
Revises: 5ae416fee83c
Create Date: 2026-03-26 15:53:52.029043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feeb34b76742'
down_revision: Union[str, Sequence[str], None] = '5ae416fee83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme', sa.Column('schedule_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('scheme', sa.Column('schedule_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheme', 'schedule_time')
    op.drop_column('scheme', 'schedule_enabled')
    # ### end Alembic commands ###
